### ISSUE TITLE
Switch airbnb-js-shims to core-js

### ISSUE THREAD

**Issue by caub** [ljharb/jellobot#14]
core-js becomes a primary source for official polyfills

example: https://github.com/tc39/proposal-array-grouping#polyfill

I suggest we switch to it

**Comment by ljharb** [comment]
lol what, no it hasn’t. There is no “primary” source for official polyfills.

i just haven’t PRd into that readme yet https://npmjs.com/array.prototype.group and https://npmjs.com/array.prototype.grouptomap (it was renamed this week).

We shouldn’t and won’t switch to it.
