### ISSUE TITLE
add caniuse plugin

### ISSUE THREAD

**Issue by ljharb** [ljharb/jellobot#8]
We should add `!ciu x` / `!caniuse x` to report caniuse results, like ecmabot had.

**Comment by caub** [comment]
notes for me

- [ ] add ciu based on https://github.com/oftn-oswg/oftn-bot/blob/master/lib/caniuse/index.js
- [ ] remove trailing line-returns in js-eval output
- [ ] see if we can give link to sources (github generally) in npm plugin
